
export const SYSTEM_SET_CONFIG = "SYSTEM_SET_CONFIG";
export const THEME_OPEN_MODAL = 'THEME_OPEN_MODAL';
export const THEME_CLOSE_MODAL = 'THEME_CLOSE_MODAL';

export const THEME_OPEN_POST_CONTROLLS_MODAL = 'THEME_OPEN_POST_CONTROLLS_MODAL';
export const THEME_CLOSE_POST_CONTROLLS_MODAL = 'THEME_CLOSE_POST_CONTROLLS_MODAL';

export const THEME_OPEN_PROFILE_MENU = 'THEME_OPEN_PROFILE_MENU';
export const THEME_CLOSE_PROFILE_MENU = 'THEME_CLOSE_PROFILE_MENU';

export const THEME_OPEN_LIKE_MODAL = 'THEME_OPEN_LIKE_MODAL';
export const THEME_CLOSE_LIKE_MODAL = 'THEME_CLOSE_LIKE_MODAL';

export const THEME_OPEN_VIEW_MODAL = 'THEME_OPEN_VIEW_MODAL';
export const THEME_CLOSE_VIEW_MODAL = 'THEME_CLOSE_VIEW_MODAL';

export const THEME_OPEN_SHARE_MODAL = 'THEME_OPEN_SHARE_MODAL';
export const THEME_CLOSE_SHARE_MODAL = 'THEME_CLOSE_SHARE_MODAL';

export const THEME_OPEN_FOLLOWERS_MODAL = 'THEME_OPEN_FOLLOWERS_MODAL';
export const THEME_CLOSE_FOLLOWERS_MODAL = 'THEME_CLOSE_FOLLOWERS_MODAL';

export const THEME_OPEN_FOLLOWING_MODAL = 'THEME_OPEN_FOLLOWING_MODAL';
export const THEME_CLOSE_FOLLOWING_MODAL = 'THEME_CLOSE_FOLLOWING_MODAL';

export const THEME_OPEN_WALLET_MENU = 'THEME_OPEN_WALLET_MENU';
export const THEME_CLOSE_WALLET_MENU = 'THEME_CLOSE_WALLET_MENU';

export const SYSTEM_LOADER_START = 'SYSTEM_LOADER_START';
export const SYSTEM_LOADER_STOP = 'SYSTEM_LOADER_STOP';
export const SYSTEM_LOADER_PROGRESS = 'SYSTEM_LOADER_PROGRESS';

